name: Push Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get Date
      id: date
      run: |
        TZ=Asia/Shanghai
        echo "::set-output name=date::$(date +'%m-%d')"

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: DockerFiles
        platforms: linux/arm64,linux/amd64
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/efb-qq
          ${{ secrets.DOCKER_USERNAME }}/efb-qq:${{ steps.date.ouyputs.date }}

  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 5